package packageEL2;

import java.io.IOException;
import java.util.ArrayList;

import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import java.util.*;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.testng.annotations.Test;

import com.fasterxml.jackson.core.JsonProcessingException;

public class Runner extends BaseClass {

//	@BeforeMethod
//	public static void ChromeLaunch() {
//		BaseClass.BrowserLaunch();
// 
//	}

	@Test(priority = 2)
	public void EPIC1489() throws Exception {
		Pom login = new Pom(driver);
		login.PAR_Order_Create();
		Await();
		login.PEGALogin();
		login.LaunchWarehousePortal();
		login.OrdersPAR();
		login.InboundTrailer_WorkQueue();
		login.Clipboard_Validation();
		login.Click_PAR_PyWorkpage();
		login.ScanTool_StatusValidation(); // scan tool PAR_Order_Create won't get trigger as it is disabled - Assert
											// failure happens
	}

	@SuppressWarnings("static-access")
	@Test(priority = 1)
	public void Epic1113() throws Exception {
		Pom login = new Pom(driver);
		login.DFDScanTool_API();
		login.XML_Write();
		login.logIntoPegaUsingValidCredentials();
		Await();
		login.ClickonRecentsIcon.click();
		login.OrderServicePage();
	//	login.DevStudioSearchBox();
		login.clickOrderServicePageActions();

		login.SOAPServicePopup();
		WebElement textArea = driver
				.findElement(By.xpath("//textarea[@name='$PpySimulationDataPage$ppyRequestTextData']"));
		// Specify the file path
		String filePath = "C:\\Users\\palanga\\eclipse-workspace\\Sprint-35\\ExceptionHandling.xml";

		// Call the sendKeysJavascript method with the appropriate arguments
		login.sendKeysJavascript(driver, textArea, filePath);
		login.ClickExecute();
		login.launchWarehousePortal();
		login.OrdersDFD();
		login.EFM_Clipboard_Status_Validation();
		
		driver.close();
		Await();
		ArrayList<String> tab1 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab1.get(2));
		login.driver.switchTo().defaultContent();
		Await();
		Pom.frameswitch2();
		Await();
		login.AwaitingArrival_Validation();
		Await();
		login.Received_Status();
		Await();
		login.ClickonCalendar.click();
		login.Calendarss();
		login.SubmitandGo_Click();
		login.Received_Status_Validation();
		Await();
		login.DeliveryScheduled_Status();
		login.SubmitandGo_Click();
		login.OrderStatus_DeliveryScheduled_Validation();
		Await();
		login.CustomerDelivery_Status_Pickup();
		Await();
		login.ClickonCalendar_POD_review.click();
		login.Calendarss();
		login.SubmitandGo_Click();
		login.CustomerDelivery_Status_OutForDelivery();
		Await();
		login.ClickonCalendar_POD_review.click();
		login.Calendarss();
		login.SubmitandGo_Click();
		login.OrderStatus_OutForDelivery_Validation();
		Await();
		login.CustomerDelivery_Status_Consignee();
		Await();
		login.ClickonCalendar_POD_review.click();
		login.Calendarss();
		login.SubmitandGo_Click();
		login.Delivered_Status();
		Await();
		login.ClickonCalendar_POD_review.click();
		login.Calendarss();
		Await();
		login.scrollToElementAndClick(driver, login.Submit);
		Await();
		login.driver.switchTo().defaultContent();
		login.frameswitch2();
		login.Resolved_Completed();
		
	}

	// EPICPLTFRM-2030 EFM POD SIGNATURE
	@SuppressWarnings("static-access")
	@Test(priority = 6)
	public void Epic2030() throws Exception {
		Pom login = new Pom(driver);
		DFD_EFM_API();
		POD_SIGNATURE_XML_Write();
		login.logIntoPegaUsingValidCredentials();
		Await();
		login.ClickonRecentsIcon.click();
		login.OrderServicePage();
	//	login.DevStudioSearchBox();
		login.clickOrderServicePageActions();
		login.SOAPServicePopup();
		WebElement textArea = driver
				.findElement(By.xpath("//textarea[@name='$PpySimulationDataPage$ppyRequestTextData']"));
		// Specify the file path
		String filePath = "C:\\Users\\palanga\\eclipse-workspace\\Sprint-35\\EFM_POD_Signature.xml";

		// Call the sendKeysJavascript method with the appropriate arguments
		login.sendKeysJavascript(driver, textArea, filePath);
		login.ClickExecute();
		login.launchWarehousePortal();
		login.OrdersDFD();
		login.EFM_Clipboard_Status_Validation();
		driver.close();
		Await();
		ArrayList<String> tab1 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab1.get(2));
		login.driver.switchTo().defaultContent();
		Await();
		Pom.frameswitch2();
		Await();
		login.AwaitingArrival_Validation();
		Await();
		login.Received_Status();
		Await();
		login.ClickonCalendar.click();
		login.Calendarss();
		login.SubmitandGo_Click();
		login.Received_Status_Validation();
		Await();
		login.DeliveryScheduled_Status();
		login.SubmitandGo_Click();
		login.OrderStatus_DeliveryScheduled_Validation();
		Await();
		login.CustomerDelivery_Status_Pickup();
		Await();
		login.ClickonCalendar_POD_review.click();
		login.Calendarss();
		login.SubmitandGo_Click();
		login.CustomerDelivery_Status_OutForDelivery();
		Await();
		login.ClickonCalendar_POD_review.click();
		login.Calendarss();
		login.SubmitandGo_Click();
		login.OrderStatus_OutForDelivery_Validation();
		Await();
		login.CustomerDelivery_Status_Consignee();
		Await();
		login.ClickonCalendar_POD_review.click();
		login.Calendarss();
		login.SubmitandGo_Click();
		login.Delivered_Status();
		Await();
		login.ClickonCalendar_POD_review.click();
		login.Calendarss();
		Await();
		login.scrollToElementAndClick(driver, login.Submit);
		Await();
		login.driver.switchTo().defaultContent();
		login.frameswitch2();
		login.Resolved_Completed();
	}

	@SuppressWarnings("static-access")
	@Test(priority = 3)
	public void Epic1489() throws Exception {
		Pom login = new Pom(driver);
		login.PAR_Order_Create();
		login.PEGALogin();
		login.LaunchWarehousePortal();
		login.OrdersPAR();
		login.InboundTrailer_WorkQueue();
		login.frameswitch2();
		Thread.sleep(7000);

		login.Received_Status();

		Await();
		login.ClickonCalendar.click();
		login.Calendarss();
		Await();
		login.getAttribute();
		login.Submit.click();
		Await();
		driver.switchTo().defaultContent();
		login.Reports.click();
		Await();
		login.frames3();
		Await();
		login.Reports_MovetoActions.click();
		Await();
		login.Click_CrowleyReports.click();

		Await();
		login.SwitchTo_CrowleyFrame();
		Await();
		login.Report_CaseIDFilterIcon.click();
		Await();
		Await();
		Await();
		Await();
		Await();
		login.Report_Click_CaseIDFilter.click();
		Await();
		Await();
		Await();
		Await();
		login.Report_Click_SearchTextFilter.click();
		login.Report_Click_SearchTextFilter.sendKeys(Pom.OrderID);
		Await();
		Await();
		login.CrowApplyClick.click();
		Await();
		login.ReceivedtableDatafetch();
		Await();
		driver.switchTo().defaultContent();
		login.SwitchtoOrderPage();
		login.frameswitch2();
		Await();
		login.OutboundLoads_Go.click();
		Await();
		driver.switchTo().defaultContent();
		login.frameswitch2();
		
		Await();
		login.Loaded_Status();
		Await();
		login.Outbound_Trailer();
		Await();
		login.Outbound_Carrier();
		
		scrollToElementAndClick(driver, login.Submit);
		
		login.Submit.click();
		Await();
		login.ClickonGo.click();
		Await();
		login.driver.switchTo().defaultContent();
		login.frameswitch2();
		login.Loaded_Status_Validation();
		Await();
		
		
		login.Released_Status();
		Await();
		login.getAttribute();
		login.Submit.click();
		Await();
		driver.switchTo().defaultContent();
		Await();
		login.Switchto_CrowleyReport_Page.click();
		Await();
		Await();
		login.SwitchTo_CrowleyFrame();
		Await();
		login.ClickReport_Actions.click();
		Await();
		login.ClickReport_Refresh.click();
		Await();
		login.SwitchTo_CrowleyFrame();
		Await();
		login.Report_CaseIDFilterIcon.click();
		Await();
		Await();
		Await();
		Await();
		Await();
		login.Report_Click_CaseIDFilter.click();
		Await();
		Await();
		Await();
		Await();
		login.Report_Click_SearchTextFilter.click();
		login.Report_Click_SearchTextFilter.sendKeys(Pom.OrderID);
		Await();
		Await();
		login.CrowApplyClick.click();
		Await();
		login.ReleasedtableDatafetch();

	}

	@SuppressWarnings("static-access")
	@Test(priority = 4)
	public void EPIC1735() throws Exception {// Mode = LTL
		Pom pom = new Pom(driver);
		pom.PAR_Order_Create();
		Await();
		pom.PEGALogin();
		pom.LaunchWarehousePortal();
		pom.OrdersPAR();
		pom.InboundTrailer_WorkQueue();
		pom.frameswitch2();
		Thread.sleep(7000);

		pom.Received_Status();
		Await();
		pom.ClickonCalendar.click();
		pom.Calendarss();
		Await();

		pom.getAttribute();
		pom.Submit.click();
		Await();
		pom.ClickonGo.click();
		pom.driver.switchTo().defaultContent();
		Await();
		pom.frameswitch2();
		
		Await();
		pom.Loaded_Status();
		Await();
		pom.Outbound_Trailer();
		Await();
		pom.Outbound_Carrier();
		
		scrollToElementAndClick(driver, pom.Submit);
		
		pom.Submit.click();
		Await();
		pom.ClickonGo.click();
		Await();
		pom.driver.switchTo().defaultContent();
		pom.frameswitch2();
		pom.Loaded_Status_Validation();
		Await();
		
		Await();
		pom.Released_Status();
		Await();
		pom.ClickonCalendar.click();
		pom.Calendarss();
		Await();
		pom.Submit.click();
		Await();
		pom.ClickonGo.click();
		Await();
		driver.switchTo().defaultContent();
		Await();
		pom.SwitchtoOrdersPAR();
		pom.driver.switchTo().defaultContent();
		Await();
		pom.frameSwitch();
		Await();
		pom.SwitchtoPODReview();
		pom.driver.switchTo().defaultContent();
		Await();
		// pom.PAR_Refresh();
		pom.frameSwitch();
		Await();
		pom.PAR_OrderSearchandFilter();
		Await();
		pom.Validate_Status_Released();
		pom.Validate_Attachment_No();
		Await();
		pom.CheckBox_Click.click();
		Await();
		pom.Attach_POD_Click.click();
		Await();
//		pom.Attachment_Clip();
		pom.Attach_File();
//		pom.Rich_Text();
		pom.Attachment_Save();
		Await();
		pom.PAR_OrderSearchandFilter();
		Await();
		pom.Validate_Attachment_Yes();
		Await();
		// pom.Attachment_Clip();
//		Await();
//		pom.Validation_Attachment_Note();
		pom.driver.switchTo().defaultContent();
		pom.SwitchtoOrderPage();
		pom.frameswitch2();
		Await();
		pom.ActionsButton();
		Await();
		pom.driver.switchTo().defaultContent();
		pom.frameswitch2();
		Await();
		pom.ClickonGo.click();
		Await();
//		pom.driver.switchTo().defaultContent();
//		pom.frameswitch2();
		Pom.ClickonCalendar_POD_review.click();
		Pom.Select2DaysagoDate();
		Await();
		Pom.ClickonCalendar_POD_review.click();
		Pom.Select2DaysagoDate();
		Await();
		pom.Release_Carrier();
		Pom.Submit.click();
		pom.driver.switchTo().defaultContent();
		Await();
		pom.frameswitch2();
		pom.OutboundLoads_Go.click();
		Await();
		pom.driver.switchTo().defaultContent();
		pom.SwitchtoOrdersPAR();
		Await();
		pom.frameSwitch();
		Await();
		Await();
		pom.OrderSearchandClear();
		Await();
		pom.OSD.click();
		pom.SwitchtoPODReview();
//		pom.OrderSearchandFilter();
		Await();
		pom.POD_Resubmitted();
		Await();
		pom.CheckBox_Click.click();
		Await();
		pom.Approve_POD_Click.click();
		Await();
		pom.ResolvePAROrder_Submit.click();
		Await();
		pom.Validate_ResolvePAROrder_ErrorMessage();

	}
	
	@SuppressWarnings("static-access")
	@Test
	public void PAR_Button() throws Exception {
		Pom pom = new Pom(driver);
		pom.PAR_Order_Create();
		Await();
		pom.PEGALogin();
		pom.LaunchWarehousePortal();
		pom.OrdersPAR();
		pom.InboundTrailer_WorkQueue();
		pom.frameswitch2();
		Thread.sleep(7000);
	}

	@SuppressWarnings("static-access")
	@Test(priority = 5)
	public void EPIC1739() throws Exception { // Mode LTL
		Pom pom = new Pom(driver);
		pom.PAR_Order_Create();
		Await();
		pom.PEGALogin();
		pom.LaunchWarehousePortal();
		pom.OrdersPAR();
		pom.InboundTrailer_WorkQueue();
		pom.frameswitch2();
		Thread.sleep(7000);
		pom.PickUpScheduled_Validation();
		driver.switchTo().defaultContent();
		pom.SwitchtoOrdersPAR();
		pom.driver.switchTo().defaultContent();
		Await();
		pom.frameSwitch();
		Await();
		pom.OrderSearchandFilter();
		Await();
		pom.CheckBox_Click.click();
		Await();
		pom.ReceiveOrder_Click.click();
		Await();
		pom.ClickonCalendar.click();
		pom.ClickonTodayDate.click();
		Await();
		String ReceivedDate = pom.Get_Received_DateandTime.getText();
		System.out.println(ReceivedDate);
		pom.Button_Receive.click();
		Await();
		pom.OutBound_Loads.click();
		pom.PAR_OrderSearchandFilter();
		Await();
		pom.Received_OBStatus_Validation();
		Await();
		pom.CheckBox_Click.click();
		Await();
		pom.AssignCarrier();
		Await();
		pom.CheckBox_Click.click();
		Await();
		pom.AssignOBTrailer();
		Await();
		driver.switchTo().defaultContent();
		pom.SwitchtoOrderPage();
		pom.driver.switchTo().defaultContent();
		Pom.frameswitch2();
		Await();
		Thread.sleep(7000);
		Await();
		pom.ActionsButton();
		Await();
		pom.driver.switchTo().defaultContent();
		pom.frameswitch2();
		Await();
		pom.ClickonGo.click();
		Await();
		pom.driver.switchTo().defaultContent();
		pom.frameswitch2();
		pom.Loaded_Status_Validation();
		Await();
		driver.switchTo().defaultContent();
		Await();
		pom.SwitchtoOrdersPAR();
		pom.driver.switchTo().defaultContent();
		Await();
		pom.frameSwitch();
		pom.CheckBox_Click.click();
		pom.Unload();
		pom.NullValidation();
		Await();
		pom.Received_OBStatus_Validation();
		Await();
		pom.CheckBox_Click.click();
		Await();
		pom.AssignCarrier();
		Await();
		pom.CheckBox_Click.click();
		Await();
		pom.AssignOBTrailer();
		Await();
		driver.switchTo().defaultContent();
		pom.SwitchtoOrderPage();
		pom.driver.switchTo().defaultContent();
		Pom.frameswitch2();
		Await();
		Thread.sleep(7000);
		Await();
		pom.ActionsButton();
		Await();
		pom.driver.switchTo().defaultContent();
		pom.frameswitch2();
		Await();
		pom.ClickonGo.click();
		Await();
		pom.driver.switchTo().defaultContent();
		pom.frameswitch2();
		pom.Loaded_Status_Validation();
		Await();
		Await();
		driver.switchTo().defaultContent();
		Await();
		pom.SwitchtoOrdersPAR();
		pom.driver.switchTo().defaultContent();
		Await();
		pom.frameSwitch();
		pom.CheckBox_Click.click();
		pom.ReleasedStatus_Button();
	    Await();
		pom.SwitchtoPODReview();
		pom.driver.switchTo().defaultContent();
		Await();
		// pom.PAR_Refresh();
		pom.frameSwitch();
		Await();
		pom.PAR_OrderSearchandFilter();
		Await();
		pom.Validate_Status_Released();
		pom.Validate_Attachment_No();
		Await();
		pom.CheckBox_Click.click();
		Await();
		pom.Attach_POD_Click.click();
		Await();
		pom.Attach_File();
		pom.Attachment_Save();
		Await();
		pom.PAR_OrderSearchandFilter();
		Await();
		pom.Validate_Attachment_Yes();
		Await();
		pom.driver.switchTo().defaultContent();
		pom.SwitchtoOrderPage();
		pom.frameswitch2();
		Await();
		pom.ActionsButton();
		Await();
		pom.driver.switchTo().defaultContent();
		pom.frameswitch2();
		Await();
		pom.OrderStatus_PODReceived();
		pom.ClickonGo.click();
		Await();
//		Pom.ClickonCalendar_POD_review.click();
//		Pom.Select2DaysagoDate();
//		Await();
//		Pom.ClickonCalendar_POD_review2.click();
//		Pom.Select2DaysagoDate();
//		Await();
//	//	pom.Release_Carrier();
    	Pom.Submit.click();
		pom.driver.switchTo().defaultContent();
		Await();
		pom.frameswitch2();
		pom.OutboundLoads_Go.click();
		Await();
		pom.driver.switchTo().defaultContent();
		pom.SwitchtoOrdersPAR();
		Await();
		pom.frameSwitch();
		Await();
		Await();
		pom.OrderSearchandClear();
		Await();
		pom.OSD.click();
		pom.SwitchtoPODReview();
		// pom.OrderSearchandFilter();
		Await();
		pom.POD_Resubmitted();
		Await();
		pom.Validate_Attachment_Yes();
		Await();
		pom.OB_LoadID();
		pom.driver.switchTo().defaultContent();
		Await();
		pom.Roundcube_Login();
		pom.OB_LoadID_Val();
	}

	@SuppressWarnings("static-access")
	@Test
	public void EPICPLTFRM_2052() throws Exception { // expected [Complete] but found
														// [Missed]Pom.Stop_Status_Complete(Pom.java:1902)
		Pom login = new Pom(driver);
		PADInbound_Order_API();
		PAD_XML_Write();
		login.PEGALogin();
		Await();
		login.ClickonRecentsIcon.click();
		login.OrderServicePage();
		login.orderService_Actions();
		login.SOAPServicePopup();
		WebElement textArea = driver
				.findElement(By.xpath("//textarea[@name='$PpySimulationDataPage$ppyRequestTextData']"));
		// Specify the file path
		String filePath = "C:\\Users\\palanga\\eclipse-workspace\\Sprint-35\\PAD_Inbound.xml";

		// Call the sendKeysJavascript method with the appropriate arguments
		login.sendKeysJavascript(driver, textArea, filePath);
		login.ClickExecute();
		Await();
		login.orderService_Actions();
		login.SOAPServicePopup();
		login.PAD_RouteStart_XML_Write();
		WebElement textArea1 = driver
				.findElement(By.xpath("//textarea[@name='$PpySimulationDataPage$ppyRequestTextData']"));
		// Specify the file path
		String RouteStartfilePath = "C:\\Users\\palanga\\eclipse-workspace\\Sprint-35\\PAD_RouteStart.xml";

		// Call the sendKeysJavascript method with the appropriate arguments
		login.sendKeysJavascript(driver, textArea1, RouteStartfilePath);
		login.ClickExecute();
		login.ClickonDatatypesIcon.click();
		Await();
		login.Clickon_Route_Datatype.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameswitch2();
		login.Clickon_Datatype_Records.click();
		Await();
		login.Clickon_Datatype_Records_Search.sendKeys(generatedId);
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		login.GloballyUniqueID();
		Await();
		login.Validate_RouteStatus();
		login.driver.switchTo().defaultContent();
		login.CloseTab();
		Await();
		login.Clickon_Stop_Datatype.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameswitch2();
		login.Clickon_Datatype_Records.click();
		Await();
		System.out.println(login.GloballyUniqueID);
		login.Clickon_Datatype_Records_Search.sendKeys(login.GloballyUniqueID);
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		login.Clickon_Datatype_Records_Search.sendKeys();
		Await();
		login.Datatype_StopID();
		login.driver.switchTo().defaultContent();
		login.CloseTab();
		Await();
		login.ClickonRecentsIcon.click();
		login.OrderServicePage();
		login.orderService_Actions();
		login.SOAPServicePopup();
		login.PAD_RouteEnd_XML_Write();
		WebElement textArea2 = driver
				.findElement(By.xpath("//textarea[@name='$PpySimulationDataPage$ppyRequestTextData']"));
		// Specify the file path
		String RouteEndfilePath = "C:\\Users\\palanga\\eclipse-workspace\\Sprint-35\\Route_End.xml";

		// Call the sendKeysJavascript method with the appropriate arguments
		login.sendKeysJavascript(driver, textArea2, RouteEndfilePath);
		login.ClickExecute();
		Await();
		login.CloseTab();
		login.Clickon_Stop_Datatype.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameswitch2();
		login.Clickon_Datatype_Records.click();
		Await();
		login.Clickon_Datatype_Records_Search.sendKeys(login.GloballyUniqueID);
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		// login.Stop_Status_Complete();
		login.driver.switchTo().defaultContent();
		login.CloseTab();
		Await();
		login.ClickonRecentsIcon.click();
		login.OrderServicePage();
		login.orderService_Actions();
		login.SOAPServicePopup();
		login.PAD_RouteEnd_XML_CMD6Update();
		WebElement textArea3 = driver
				.findElement(By.xpath("//textarea[@name='$PpySimulationDataPage$ppyRequestTextData']"));
		// Call the sendKeysJavascript method with the appropriate arguments
		login.sendKeysJavascript(driver, textArea3, RouteEndfilePath);
		login.ClickExecute();
		Await();
		login.CloseTab();
		login.Clickon_Stop_Datatype.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameswitch2();
		login.Clickon_Datatype_Records.click();
		Await();
		Await();
		login.Clickon_Datatype_Records_Search.sendKeys(login.GloballyUniqueID);
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		// login.Stop_Status_EnRoute();
		login.driver.switchTo().defaultContent();
		login.CloseTab();
		Await();
		login.ClickonRecentsIcon.click();
		login.OrderServicePage();
		login.orderService_Actions();
		login.SOAPServicePopup();
		login.PAD_RouteEnd_XML_CMD7Update();
		WebElement textArea4 = driver
				.findElement(By.xpath("//textarea[@name='$PpySimulationDataPage$ppyRequestTextData']"));
		// Call the sendKeysJavascript method with the appropriate arguments
		login.sendKeysJavascript(driver, textArea4, RouteEndfilePath);
		login.ClickExecute();
		Await();
		login.CloseTab();
		login.Clickon_Stop_Datatype.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameswitch2();
		login.Clickon_Datatype_Records.click();
		Await();
		Await();
		login.Clickon_Datatype_Records_Search.sendKeys(login.GloballyUniqueID);
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
//		login.Stop_Status_Arrived();
		login.driver.switchTo().defaultContent();
		login.CloseTab();
		Await();
		login.ClickonRecentsIcon.click();
		login.OrderServicePage();
		login.orderService_Actions();
		login.SOAPServicePopup();
		login.PAD_RouteEnd_XML_CMD9Update();
		WebElement textArea5 = driver
				.findElement(By.xpath("//textarea[@name='$PpySimulationDataPage$ppyRequestTextData']"));
		// Call the sendKeysJavascript method with the appropriate arguments
		login.sendKeysJavascript(driver, textArea5, RouteEndfilePath);
		login.ClickExecute();
		Await();
		login.CloseTab();
		login.Clickon_Stop_Datatype.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameswitch2();
		login.Clickon_Datatype_Records.click();
		Await();
		Await();
		login.Clickon_Datatype_Records_Search.sendKeys(login.GloballyUniqueID);
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		login.Stop_Status_Missed();
	}

	@SuppressWarnings("static-access")
	@Test
	public void EPICPLTFRM_2081() throws Exception {
		Pom login = new Pom(driver);
		login.PAR_Order_Create();
		// Await();
		// login.Update_Loaded_PAR_Order_Create();
		Await();
		login.PEGALogin();
		Await();
		login.ClickonDatatypesIcon.click();
		Await();
		login.Clickon_Status_Datatype.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		login.Clickon_Datatype_Records.click();
		Await();
		Await();
		login.Clickon_Datatype_Records_Search.sendKeys(login.OrderID);
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		login.Status_Validate();
		Await();
		login.CloseTab();
		login.driver.switchTo().defaultContent();
		Await();
		login.LaunchWarehousePortal();
		login.OrdersPAR();
		login.OutboundTrailer_Tab();
		login.Clipboard_Loaded_Validation();
	}

	@SuppressWarnings("static-access")
	@Test
	public void PAD_NewStatus() throws Exception {
		Pom login = new Pom(driver);
		login.PAD_NewOrder();
		Await();
		login.PEGALogin();
		login.LaunchWarehousePortal();
		login.OrdersPAD();
		Await();
		Pom.frameswitch2();
		Await();
		login.DeliveryScheduled_Status();
		Await();
		scrollToElementAndClick(driver, login.Submit);
		Await();
		login.ClickonGo.click();
		Await();
		login.driver.switchTo().defaultContent();
		Await();
		Pom.frameswitch2();
		Await();
		login.CustomerDelivery_Status_Pickup();
		Await();

		login.ClickonCalendar_POD_review.click();
		login.Calendarss();
		Await();
		Await();
		scrollToElementAndClick(driver, login.Submit);
		Await();
		login.ClickonGo.click();
		login.driver.switchTo().defaultContent();
		Await();
		Pom.frameswitch2();
		Await();
		login.OrderStatus_DeliveryScheduled_Validation();
		Await();
		login.driver.switchTo().defaultContent();
		Await();
		login.Clipboard_Validation();
		login.Click_PAD_PyWorkpage();
		login.OrderPage_StatusEvent_DeliveryScheduled_StatusValidation();
		Await();
		ArrayList<String> tab1 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab1.get(1));
		login.driver.switchTo().defaultContent();
		Pom.frameswitch2();
		Await();
		login.CustomerDelivery_Status_OutForDelivery();
	
		Await();
		Await();
		scrollToElementAndClick(driver, login.Submit);
		Await();
		login.ClickonGo.click();
		login.driver.switchTo().defaultContent();
		Await();
		Pom.frameswitch2();
		Await();
		login.OrderStatus_OutForDelivery_Validation();
		Await();
		login.driver.switchTo().defaultContent();
		Await();
		login.Clipboard_Click_PAD();
		login.OrderPage_StatusEvent_OutForDelivery_StatusValidation();
		Await();
		ArrayList<String> tab2 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab2.get(1));
		login.driver.switchTo().defaultContent();
		Pom.frameswitch2();
		Await();
		login.CustomerDelivery_Status_Consignee();
		Await();
		Await();
		scrollToElementAndClick(driver, login.Submit);
		Await();
		login.ClickonGo.click();
		login.driver.switchTo().defaultContent();
		Await();
		Pom.frameswitch2();
		Await();
		login.OrderStatus_OutForDelivery_Validation();
		login.driver.switchTo().defaultContent();
		Await();
		login.Clipboard_Click_PAD();
		login.OrderPage_StatusEvent_OutForDelivery_StatusValidation();
		Await();
		ArrayList<String> tab3 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab3.get(1));
		login.driver.switchTo().defaultContent();
		Pom.frameswitch2();
		Await();
		login.Delivered_Status();
		Await();
		login.ClickonCalendar_POD_review.click();
		login.Calendarss();
		Await();
		Await();
		scrollToElementAndClick(driver, login.Submit);
		Await();
		login.driver.switchTo().defaultContent();
		Await();
		Pom.frameswitch2();
		Await();
		login.Rated_Status_Validation();
		login.driver.switchTo().defaultContent();
		Await();

		ArrayList<String> tab = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab.get(0));
		Await();
		login.ClickonDatatypesIcon.click();
		Await();
		login.Clickon_Status_Datatype.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
		login.Clickon_Datatype_Records.click();
		Await();
		Await();
		login.Clickon_Datatype_Records_Search.sendKeys(login.OrderID);
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		Await();
		Await();
		login.Status_Validate();
	}

	@SuppressWarnings("static-access")
	@Test
	public void DFD_NewStatus() throws Exception {
		Pom login = new Pom(driver);
		login.DFD_NewOrder();
		Await();
		login.PEGALogin();
		login.LaunchWarehousePortal();
		login.OrdersDFD();
		Await();
		login.frameswitch2();
		Await();
		login.Received_Status();
		Await();
		login.ClickonCalendar.click();
		login.Calendarss();
		Await();
		scrollToElementAndClick(driver, login.Submit);
		Await();
		login.ClickonGo.click();
		login.driver.switchTo().defaultContent();
		Await();
		Pom.frameswitch2();
		Await();
		login.DeliveryScheduled_Status();
		Await();
		login.ClickonCalendar_POD_review.click();
		login.Calendarss();
		Await();
		scrollToElementAndClick(driver, login.Submit);
		Await();
		login.ClickonGo.click();
		login.driver.switchTo().defaultContent();
		Await();
		Pom.frameswitch2();
		Await();
		login.CustomerDelivery_Status_Consignee();
		Await();
		login.ClickonCalendar_POD_review.click();
		login.Calendarss();
		Await();
		Await();
		scrollToElementAndClick(driver, login.Submit);
		Await();
		login.ClickonGo.click();
		login.driver.switchTo().defaultContent();
		Await();
		Pom.frameswitch2();
		Await();
		login.OrderStatus_DeliveryScheduled_Validation();
		Await();
		login.driver.switchTo().defaultContent();
		Await();
		login.Clipboard_Validation();
		login.Click_DFD_PyWorkpage();
		login.OrderPage_StatusEvent_DeliveryScheduled_StatusValidation();
		Await();
		ArrayList<String> tab1 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab1.get(1));
		login.driver.switchTo().defaultContent();
		Pom.frameswitch2();
		Await();

		login.CustomerDelivery_Status_Pickup();
		Await();
		Await();
		scrollToElementAndClick(driver, login.Submit);
		Await();
		login.ClickonGo.click();
		login.driver.switchTo().defaultContent();
		Await();
		Pom.frameswitch2();
		Await();
		login.OrderStatus_DeliveryScheduled_Validation();
		Await();
		login.driver.switchTo().defaultContent();
		Await();
		login.Clipboard_Click_DFD();
		login.OrderPage_StatusEvent_DeliveryScheduled_StatusValidation();
		Await();
		ArrayList<String> tab2 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab2.get(1));
		login.driver.switchTo().defaultContent();
		Pom.frameswitch2();
		Await();
		login.CustomerDelivery_Status_OutForDelivery();
		Await();
		Await();
		scrollToElementAndClick(driver, login.Submit);
		Await();
		login.ClickonGo.click();
		login.driver.switchTo().defaultContent();
		Await();
		Pom.frameswitch2();
		Await();
		login.OrderStatus_OutForDelivery_Validation();
		login.driver.switchTo().defaultContent();
		Await();
		login.Clipboard_Click_DFD();
		login.OrderPage_StatusEvent_OutForDelivery_StatusValidation();
		Await();

		driver.close();
		Await();
		ArrayList<String> tab = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab.get(0));
		Await();
		login.ClickonDatatypesIcon.click();
		Await();
		login.Clickon_Status_Datatype.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
		login.Clickon_Datatype_Records.click();
		Await();
		Await();
		login.Clickon_Datatype_Records_Search.sendKeys(login.OrderID);
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		Await();
		Await();
		login.Status_Validate();
		ArrayList<String> tab3 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab3.get(1));
		login.driver.switchTo().defaultContent();
		Pom.frameswitch2();
		Await();
		login.driver.switchTo().defaultContent();
		Await();
		Pom.frameswitch2();
		Await();
		login.Delivered_Status();
		Await();
		login.CustomerDelivery_Calendar.click();
		login.Calendarss();
		Await();
		scrollToElementAndClick(driver, login.Submit);
		Await();
		login.driver.switchTo().defaultContent();
		login.frameswitch2();
		Await();
		login.ClickonGo.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameswitch2();
		login.Rated_Status_Validation();
	}

	@SuppressWarnings("static-access")
	@Test
	public void ApprovePOD_Mode_CrowleyTL() throws Exception {
		Pom login = new Pom(driver);
		login.PAR_Order_Create();
		login.Await(By.id("loginText2"));
		login.PEGALogin();
		login.LaunchWarehousePortal();
		login.OrdersPAR();
		login.InboundTrailer_WorkQueue();
		login.frameswitch2();
		Thread.sleep(7000);
		login.PickUpScheduled_Validation();
		Await();
		login.Received_Status();
		Await();
		login.ClickonCalendar.click();
		login.Calendarss();
		Await();
		login.getAttribute();
		login.Submit.click();
		Await();
		login.ClickonGo.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.Clipboard_Validation();
		login.Click_PAR_PyWorkpage();
		login.OrderPage_RequiredStatus_No_Validation();
		login.OrderPage_StatusEvent_Received_StatusValidation();
		driver.close();
		Await();
		ArrayList<String> tab = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab.get(0));
		Await();
		login.ClickonDatatypesIcon.click();
		Await();
		login.Clickon_Order_Datatype.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
		login.Clickon_Datatype_Records.click();
		Await();
		Await();
		login.Clickon_Datatype_Records_Search.sendKeys(login.OrderID);
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		Await();
		Await();
		login.Received_Date_Validation();
		Await();
		login.driver.switchTo().defaultContent();
		login.CloseTab();
		Await();
		ArrayList<String> tab1 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab1.get(1));
		login.driver.switchTo().defaultContent();
		Await();
		Pom.frameswitch2();
		Await();
		login.Loaded_Status();
	//	login.Loaded_Status();
		Await();
		login.Outbound_Trailer();
		Await();
		login.Outbound_Carrier();
		
		scrollToElementAndClick(driver, login.Submit);
		
		login.Submit.click();
		Await();
		login.ClickonGo.click();
		Await();
		login.driver.switchTo().defaultContent();
		login.frameswitch2();
		login.Loaded_Status_Validation();
		Await();
		
		login.Released_Status();
		Await();
		login.ClickonCalendar.click();
		login.Calendarss();
		Await();
		login.getAttribute();
		scrollToElementAndClick(driver, login.Submit);
		Await();
		driver.switchTo().defaultContent();
		login.frameswitch2();
		Await();
		login.ClickonGo.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameswitch2();
		Await();
		login.OrderStatus_Released_Validation();
		Await();
		login.getCalendar();
		login.Submit.click();
		driver.switchTo().defaultContent();
		Await();
		login.SwitchtoOrdersPAR();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
		login.SwitchtoPODReview();
		login.driver.switchTo().defaultContent();
		Await();
		login.CrowleyTLPOD.click();
		Await();
		driver.switchTo().frame(driver.findElement(By.xpath("//iframe[@name='PegaGadget2Ifr']")));
	//	pom.frameswitch2();
		login.EnterIBLoadID.sendKeys(Keys.ENTER);
		login.EnterIBLoadID.sendKeys(login.Invoice_number);
	    Await();
	    login.Search_IBLoadID.click();
	    Await();	
	    login.ResolvePAROrder_Submit.click();
	    Await();
	    
	    login.AttachFile_POD.sendKeys("C:\\Users\\palanga\\eclipse-workspace\\Sprint-35\\File\\List of Outbound Loads (4).pdf");
		Await();
	//	-----------------------------------DEBUG---------------------------------
		login.ResolvePAROrder_Submit.click();
		Await();	
		login.driver.switchTo().defaultContent();
		login.SwitchtoOrdersPAR();
		Await();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
		login.Order_Tab_Refresh.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
		login.PAR_OrderSearchandFilter();
		Await();
		login.Validate_Attachment_Yes();
		Await();
		Await();
		login.POD_Received();
		Await();
		login.CheckBox_Click.click();
		Await();
		login.Validate_ApprovePOD();
		Await();
		login.ResolvePAROrder();
		Await();
		login.Validate_ResolvePAROrder_ErrorMessage();
		Await();
		login.Close_AttachmentList_Box.click();
		driver.switchTo().defaultContent();
		ArrayList<String> tab2 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab2.get(0));
		Await();    
		Await();
		login.DevStudioSearchBox("ConfrimPOD", login.ClickConfirmPOD);
		login.orderService_Actions();
		driver.switchTo().defaultContent();
		Await();
		System.out.println(driver.getWindowHandles().size());
		login.getWindow_Parent();
		Await();
		login.switchToLatestWindow();
		Await();
		login.pyIDTextBox.click();
		System.out.println("Clicked");
		login.pyIDTextBox.sendKeys(login.OrderID);
		login.PODConfirmNum_TextBox.click();
		double POD_number = Math.ceil(Math.random() * 1000000);
		String POD_ConfirmNumber = Double.toString(POD_number);
		login.PODConfirmNum_TextBox.sendKeys(POD_ConfirmNumber);
		System.out.println("Order ID entered");
		login.Actions_Run.click();
		Await();
		driver.close();
		driver.switchTo().window(parentWindow);
		driver.switchTo().defaultContent();
		ArrayList<String> tab3 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab3.get(1));
		Await();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		login.Order_Tab_Refresh.click();
		Await();        
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
		login.PAR_OrderSearchandFilter();
		Await();
		login.Validate_POD_Accepted();
		Await();
		login.CheckBox_Click.click();
		Await();
		login.Validate_ApprovePOD();
		Await();
		login.ApprovePAR_Submit.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.switchtoOrdersPage();
		login.frameswitch2();
		Thread.sleep(7000);
		Await();
		login.ActionsButton();
		Await();
		Await();
		login.driver.switchTo().defaultContent();
		login.frameswitch2();
		login.Resolved_Completed();
	}

	@SuppressWarnings("static-access")
	@Test
	public void Smoke_LTL() throws Exception {
		Pom pom = new Pom(driver);
		pom.PAR_Order_Create(); // LTL Mode
		pom.Await(By.id("loginText2"));
		pom.PEGALogin();
		pom.LaunchWarehousePortal();
		pom.OrdersPAR();
		pom.InboundTrailer_WorkQueue();
		pom.frameswitch2();
		Thread.sleep(7000);
		pom.PickUpScheduled_Validation();
		Await();
		pom.StatusUpdate_Received();
		pom.StatusUpdate_Process();
		pom.Received_Status_Validation();
		pom.ClickonGo.click();
		pom.driver.switchTo().defaultContent();
		pom.frameswitch2();
		Await();
		pom.getAttribute();
		
		pom.driver.switchTo().defaultContent();
		Await();
		pom.Clipboard_Validation();
		pom.Click_PAR_PyWorkpage();
		pom.OrderPage_RequiredStatus_No_Validation();
		pom.PyPage_Received_StatusDateTime();
		pom.OrderPage_StatusEvent_Received_StatusValidation();
		pom.OrderPage_Arrive_OutforDel_Date();
		driver.close();
		Await();
		ArrayList<String> tab = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab.get(0));
		Await();
	//	pom.Close_PARtab1.click();
		Await();
		pom.ClickonDatatypesIcon.click();
		Await();
		pom.Clickon_Order_Datatype.click();
		pom.driver.switchTo().defaultContent();
		Await();
		pom.frameSwitch();
		Await();
		pom.Clickon_Datatype_Records.click();
		Await();
		Await();
		pom.Clickon_Datatype_Records_Search.sendKeys(pom.OrderID);
		pom.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		Await();
		Await();
	//	pom.Received_Date_Validation();
	//	pom.ArrivedAtPickup_Date_Validation();
		pom.OrderPage_Arrive_OutforDel_Date_Validation();
		Await();
		driver.switchTo().defaultContent();
		pom.Close_PARtab1.click();
		Await();
		ArrayList<String> tab1 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab1.get(1));
		pom.driver.switchTo().defaultContent();
		Await();
		Pom.frameswitch2();
		Await();
		pom.StatusUpdate_Released();
		pom.StatusUpdate_Process();
		pom.OrderStatus_Released_Validation();
		
		pom.ClickonGo.click();
		pom.driver.switchTo().defaultContent();
		pom.frameswitch2();
		Await();
		pom.Release_Carrier();
		Await();
		scrollToElementAndClick(driver, pom.Submit);
		pom.Submit.click();
		Await();
		
		pom.driver.switchTo().defaultContent();
		Await();
		Await();
		pom.Clipboard_Click();
		pom.OrderPage_RequiredStatus_Yes_Validation();

		Await();
		pom.ExpandpyworkPage.click();
		Await();
		pom.ClickonOrderpageinCipboard.click();
		Await();
		pom.OrderPage_StatusEvent_Released_StatusValidation();
		driver.close();
		Await();
		
		ArrayList<String> tab9 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab9.get(1));
		driver.switchTo().defaultContent();
		Await();
		pom.SwitchtoOrdersPAR();
		pom.driver.switchTo().defaultContent();
		Await();
		pom.frameSwitch();
		Await();
		
	//------------------------------------------------>
		
		pom.SwitchtoPODReview();
		pom.driver.switchTo().defaultContent();
		Await();
		pom.frameSwitch();
		Await();
		pom.OrderSearchandFilter();
		Await();
		
		pom.Validate_Status_Released();
		pom.Validate_Attachment_No();
		Await();
		pom.CheckBox_Click.click();
		Await();
		pom.Attach_POD_Click.click();
		Await();
		pom.Attach_File();
		pom.Attachment_Save();
		Await();
		pom.OrderSearchandFilter();
		Await();
		pom.Validate_Attachment_Yes();
		Await();
		pom.OrderSearchandClear();
		Await();
		pom.OSD.click();
		pom.SwitchtoPODReview();
		pom.driver.switchTo().defaultContent();
		Await();
		pom.frameSwitch();
		Await();
		pom.POD_Received();
		Await();
		pom.Validate_Attachment_Yes();
		Await();
		pom.driver.switchTo().defaultContent();
		Await();
		pom.switchtoOrdersPage();
		Await();
		pom.frameswitch2();
		Thread.sleep(7000);
		Await();
		pom.ActionsButton();
		Await();
		pom.driver.switchTo().defaultContent();
		pom.frameswitch2();
		Await();
		pom.OrderStatus_PODReceived();
		Await();
		pom.driver.switchTo().defaultContent();
		pom.Clipboard_Click();
		Await();
		pom.ExpandpyworkPage.click();
		Await();
		pom.ClickonOrderpageinCipboard.click();
		Await();
		pom.OrderPage_StatusEvent_Released_StatusValidation();
		driver.close();
		Await();
		ArrayList<String> tab10 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab10.get(1));
		driver.switchTo().defaultContent();
		Await();
		pom.SwitchtoOrdersPAR();
		pom.driver.switchTo().defaultContent();
		Await();
		pom.frameSwitch();
		Await();
		pom.CheckBox_Click.click();
		Await();
		pom.Re_Submit_POD_Click.click();
		Await();
		pom.Re_Submit.click();
		Await();
		pom.Re_Submit_Validation();
		Await();
		pom.Click_ViewDoc();
		Await();
		pom.Download_and_Delete_Document_Attached();
		pom.Validate_Status_Released();
		
		pom.Validate_Attachment_No();
		Await();
		pom.CheckBox_Click.click();
		Await();
		pom.Attach_POD_Click.click();
		Await();
		pom.Attach_File();
		pom.Attachment_Save();
		Await();
		
		driver.switchTo().defaultContent();
		ArrayList<String> tab2 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab2.get(0));
		Await();    
		Await();
		pom.DevStudioSearchBox("ConfrimPOD", pom.ClickConfirmPOD);  
		pom.orderService_Actions();
		driver.switchTo().defaultContent();
		Await();
		System.out.println(driver.getWindowHandles().size());
		pom.getWindow_Parent();
		Await();
		pom.switchToLatestWindow();
		Await();
		pom.pyIDTextBox.click();
		System.out.println("Clicked");
		pom.pyIDTextBox.sendKeys(pom.OrderID);
		pom.PODConfirmNum_TextBox.click();
		double POD_number = Math.ceil(Math.random() * 1000000);
		String POD_ConfirmNumber = Double.toString(POD_number);
		pom.PODConfirmNum_TextBox.sendKeys(POD_ConfirmNumber);
		System.out.println("Order ID entered");
		pom.Actions_Run.click();
		Await();
		driver.close();
		driver.switchTo().window(parentWindow);
		driver.switchTo().defaultContent();
		ArrayList<String> tab3 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab3.get(1));
		Await();
		pom.driver.switchTo().defaultContent();
		Await();
		pom.frameSwitch();
		pom.Order_Tab_Refresh.click();
		Await();        
		pom.driver.switchTo().defaultContent();
		Await();
		pom.frameSwitch();
		Await();
		pom.OrderSearchandFilter();
		Await();
		pom.Validate_POD_Accepted();
		Await();
		pom.CheckBox_Click.click();
		Await();
		pom.Validate_ApprovePOD();
		Await();
		pom.ApprovePAR_Submit.click();
		pom.driver.switchTo().defaultContent();
		Await();
		pom.switchtoOrdersPage();
		pom.frameswitch2();
		Thread.sleep(7000);
		Await();
		pom.ActionsButton();
		Await();
		Await();
		pom.driver.switchTo().defaultContent();
		pom.frameswitch2();
		pom.Resolved_Completed();
	}

	@SuppressWarnings("static-access")
	@Test
	public void SmokeTest() throws Exception {
		Pom login = new Pom(driver);
		login.PAR_Order_Create(); // LTL Mode
		// Await();
		login.Await(By.id("loginText2"));
		login.PEGALogin();
		login.LaunchWarehousePortal();
		login.OrdersPAR();
		login.InboundTrailer_WorkQueue();
		login.frameswitch2();
		
		Thread.sleep(7000);
		login.PickUpScheduled_Validation();
		Await();
		login.Received_Status();
		Await();
		login.ClickonCalendar.click();
		login.Calendarss();
		Await();
		login.getAttribute();
		login.Submit.click();
		Await();
		login.ClickonGo.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.Clipboard_Validation();
		login.Click_PAR_PyWorkpage();
		login.OrderPage_RequiredStatus_No_Validation();
		login.OrderPage_StatusEvent_Received_StatusValidation();
		driver.close();
		Await();
		ArrayList<String> tab = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab.get(0));
		Await();
		login.ClickonDatatypesIcon.click();
		Await();
		login.Clickon_Order_Datatype.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
		login.Clickon_Datatype_Records.click();
		Await();
		Await();
		login.Clickon_Datatype_Records_Search.sendKeys(login.OrderID);
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		Await();
		Await();
		login.Received_Date_Validation();
		Await();
		ArrayList<String> tab1 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab1.get(1));
		login.driver.switchTo().defaultContent();
		Await();
		Pom.frameswitch2();
		Await();
		login.Released_Status();
		Await();
		login.ClickonCalendar.click();
		login.Calendarss();
		Await();
		login.getAttribute();
		scrollToElementAndClick(driver, login.Submit);
		// login.Submit.click();
		Await();
		driver.switchTo().defaultContent();
		login.frameswitch2();
		Await();
		login.ClickonGo.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameswitch2();
		Await();
		login.OrderStatus_Released_Validation();
		Await();
		ArrayList<String> tab2 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab2.get(0));
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		Await();
		Await();
		login.ActualDelivery_Date_Validation();
		Await();
		ArrayList<String> tab3 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab3.get(1));
		login.driver.switchTo().defaultContent();
		Await();
//		Pom.frameswitch2();
		Await();
		login.Clipboard_Click();
		login.OrderPage_RequiredStatus_No_Validation();
		login.OrderPage_StatusEvent_Released_StatusValidation();
		Await();
		login.ExpandpyworkPage.click();
		Await();
		login.ClickonOrderpageinCipboard.click();
		Await();
		login.OrderPage_ReceivedDate();
		driver.close();
		Await();
		ArrayList<String> tab4 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab4.get(1));
		Await();
		driver.switchTo().defaultContent();
		Await();
		login.SwitchtoOrdersPAR();
		login.driver.switchTo().defaultContent();//------------------------------------------------>
		Await();
		login.frameSwitch();
		Await();
		login.SwitchtoPODReview();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
		login.OrderSearchandFilter();
		Await();
		login.OrderPAR_ReceivedDate();
		Await();
		login.convert_Date();
		login.driver.switchTo().defaultContent();
		Await();
		login.switchtoOrdersPage();
		Await();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameswitch2();
		Await();
		login.ClickonCalendar_POD_review.click();
		login.Calendarss();
		Await();
		login.get_Pickup_Date();
		Await();
		login.Release_Carrier();
		Await();
		// Scroll down doesn't worked

		scrollToElementAndClick(driver, login.Submit);
		// login.Submit.click();

		Await();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameswitch2();
		login.OutboundLoads_Go.click();
		Await();
		ArrayList<String> tab5 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab5.get(0));
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		Await();
		Await();
		login.ArrivedAtPickup_Date_Validation();
		Await();
		ArrayList<String> tab6 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab6.get(1));
		Await();
		driver.switchTo().defaultContent();
		Await();
		login.frameswitch2();
		Await();
		login.ClickonCalendar_POD_review.click();
		login.Calendarss();
		Await();
		login.get_OutForDelivery_Date();
		Await();
		login.Submit.click();
		Await();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameswitch2();
		login.OutboundLoads_Go.click();
		Await();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameswitch2();
		Await();
		login.OrderStatus_Released_Validation();
		Await();
		ArrayList<String> tab7 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab7.get(0));
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		Await();
		Await();
		Await();
		Await();
		login.OutForDelivery_Date_Validation();
		Await();
		ArrayList<String> tab8 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab8.get(1));
		login.driver.switchTo().defaultContent();
		Await();
		Await();
		login.Clipboard_Click();
		login.OrderPage_RequiredStatus_Yes_Validation();

		Await();
		login.ExpandpyworkPage.click();
		Await();
		login.ClickonOrderpageinCipboard.click();
		Await();
		login.OrderPage_StatusEvent_Released_StatusValidation();
		driver.close();
		Await();
		ArrayList<String> tab9 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab9.get(1));
		driver.switchTo().defaultContent();
		Await();
		login.SwitchtoOrdersPAR();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
		login.Validate_Status_Released();
		login.Validate_Attachment_No();
		Await();
		login.CheckBox_Click.click();
		Await();
		login.Attach_POD_Click.click();
		Await();
		login.Attach_File();
		login.Attachment_Save();
		Await();
		login.OrderSearchandFilter();
		Await();
		login.Validate_Attachment_Yes();
		Await();
//		login.Attachment_Clip();
//		Await();
//		login.Validation_Attachment_Note();
//		Await();
		login.OrderSearchandClear();
		Await();
		login.OSD.click();
		login.SwitchtoPODReview();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
//		login.OrderSearchandFilter();
//		Await();
		login.POD_Received();
		Await();
		login.Validate_Attachment_Yes();
		Await();
		login.driver.switchTo().defaultContent();
		Await();
		login.switchtoOrdersPage();
		Await();
		Await();
		login.Clipboard_Click();
		Await();
		login.ExpandpyworkPage.click();
		Await();
		login.ClickonOrderpageinCipboard.click();
		Await();
		login.OrderPage_StatusEvent_Released_StatusValidation();
		driver.close();
		Await();
		ArrayList<String> tab10 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab10.get(1));
		driver.switchTo().defaultContent();
		Await();
		login.SwitchtoOrdersPAR();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
		login.CheckBox_Click.click();
		Await();
		login.Re_Submit_POD_Click.click();
		Await();
		login.Re_Submit.click();
		Await();
		login.Re_Submit_Validation();
		Await();
		login.Click_ViewDoc();
		Await();
		login.Download_and_Delete_Document_Attached();
		login.Validate_Status_Released();

	}

	@SuppressWarnings("static-access")
	@Test
	public void Smoke_XML() throws Exception { // LTL
		Pom login = new Pom(driver);
		login.PAR_Order_Create();
		Await();
		login.PAR_ArrivedAtPickup_Status_Update();
		Await();
		login.PEGALogin();
		Await();
		login.ClickonRecentsIcon.click();
		login.OrderServicePage();
		login.orderService_Actions();
		login.SOAPServicePopup();

		WebElement textArea = driver
				.findElement(By.xpath("//textarea[@name='$PpySimulationDataPage$ppyRequestTextData']"));
		// Specify the file path
		String filePath = "C:\\Users\\palanga\\eclipse-workspace\\EL2-Automation\\Status_Update.xml";

		// Call the sendKeysJavascript method with the appropriate arguments
		login.sendKeysJavascript(driver, textArea, filePath);
		login.ClickExecute();
		Await();
		Await();
		login.CloseTab();
//-----------------------------------------------------
		login.ClickonDatatypesIcon.click();
		Await();
		login.Clickon_Order_Datatype.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
		login.Clickon_Datatype_Records.click();
		Await();
		Await();
		login.Clickon_Datatype_Records_Search.sendKeys(login.OrderID);
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		Await();
		Await();
		Await();
		Await();
		login.ArrivedAtPickup_Date();
		Await();
		Await();
		login.Pickup_Date_Validation();
		Await();
		login.Order_Data_Validation();
		Await();
		login.driver.switchTo().defaultContent();
		login.CloseTab();
//------------------------		
		login.Clickon_Status_Datatype.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
		login.Clickon_Datatype_Records.click();
		Await();
		Await();
		login.Clickon_Datatype_Records_Search.sendKeys(login.OrderID);
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		Await();
		Await();
		Await();
		Await();
		login.Status_Validate();
		Await();
		login.driver.switchTo().defaultContent();
		login.CloseTab();

		login.LaunchWarehousePortal();
		login.OrdersPAR();
		Await();
		login.InboundTrailer_WorkQueue();
		login.frameswitch2();
		Thread.sleep(7000);
		Await();
		login.AwaitingArrival_Validation();
		Await();
		// ===================
		login.driver.switchTo().defaultContent();
		Await();
		login.Clipboard_Validation();
		login.Click_PAR_PyWorkpage();
		login.StatusUpdatetoScanTool_Validation();
		driver.close();

		ArrayList<String> tab10 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab10.get(0));
		Await();
		login.ClickonRecentsIcon.click();
		login.OrderServicePage();
		login.orderService_Actions();
		login.SOAPServicePopup();
		login.PAR_OutForDelivery_Status_Update();
		WebElement textArea1 = driver
				.findElement(By.xpath("//textarea[@name='$PpySimulationDataPage$ppyRequestTextData']"));
		// Specify the file path
		String filePath1 = "C:\\Users\\palanga\\eclipse-workspace\\EL2-Automation\\Status_Update.xml";

		// Call the sendKeysJavascript method with the appropriate arguments
		login.sendKeysJavascript(driver, textArea1, filePath1);
		login.ClickExecute();
		Await();
		login.CloseTab();
		login.ClickonDatatypesIcon.click();
		Await();
		login.Clickon_Order_Datatype.click();
		Await();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
		login.Clickon_Datatype_Records.click();
		Await();
		Await();
		login.Clickon_Datatype_Records_Search.sendKeys(login.OrderID);
		Await();
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		Await();
		Await();
		Await();
		Await();
		login.OutForDelivery_Date();
		Await();
		login.Delivery_Date_Validation();
		Await();
		login.driver.switchTo().defaultContent();
		login.CloseTab();
		Await();
		login.Clickon_Status_Datatype.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
		login.Clickon_Datatype_Records.click();
		Await();
		Await();
		login.Clickon_Datatype_Records_Search.sendKeys(login.OrderID);
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		Await();
		Await();
		Await();
		Await();
		Await();
		login.Status_Validate();
		Await();
		login.driver.switchTo().defaultContent();
		login.CloseTab();
		Await();
		ArrayList<String> tab1 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab1.get(0));
//		login.driver.switchTo().defaultContent();

//		login.LaunchWarehousePortal();
//		login.OrdersPAR();
//		Await();
//		login.InboundTrailer_WorkQueue();
		System.out.println("switch to 0");
		ArrayList<String> tab11 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab11.get(1));
		driver.close();
		ArrayList<String> tab12 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab12.get(1));
		login.frameswitch2();
		Thread.sleep(7000);
		Await();
		login.AwaitingArrival_Validation();
		Await();
		Await();
		// -------------------------------
		login.driver.switchTo().defaultContent();
		Await();
		login.Clipboard_Click_Validation();
		login.Click_PAR_PyWorkpage();
		login.StatusUpdatetoScanTool_Validation();
		driver.close();
		// ---------------------------------
		Await();
		ArrayList<String> tab13 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab13.get(1));
		login.frameswitch2();
		Thread.sleep(7000);
		Await();
		login.ActionsButton();
		Await();
		login.driver.switchTo().defaultContent();
		login.frameswitch2();
		Await();
		login.ClickonGo.click();
		Await();
		login.Received_Status();
		Await();
		Await();
		login.ClickonCalendar.click();
		login.Calendarss();
		Await();
		login.getAttribute();
		scrollToElementAndClick(driver, login.Submit);
		login.Submit.click();
		Await();
		login.ClickonGo.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.Clipboard_Click_Validation();
		login.Click_PAR_PyWorkpage();
		login.StatusUpdatetoScanTool_Validation();
		login.OrderPage_RequiredStatus_No_Validation();
		login.OrderPage_StatusEvent_Received_StatusValidation();
		driver.close();
		Await();

		ArrayList<String> tab = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab.get(0));
		Await();
		login.ClickonDatatypesIcon.click();
		Await();
		login.Clickon_Order_Datatype.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
		login.Clickon_Datatype_Records.click();
		Await();
		Await();
		login.Clickon_Datatype_Records_Search.sendKeys(login.OrderID);
		login.Clickon_Datatype_Records_SearchIcon.click();
		Await();
		Await();
		Await();
		Await();
		Await();
		Await();
		login.Received_Date_Validation();
		Await();
		ArrayList<String> tab3 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab3.get(1));
		login.driver.switchTo().defaultContent();
		Await();
		Pom.frameswitch2();
		Await();
		login.Released_Status();
		Await();
		login.ClickonCalendar.click();
		login.Calendarss();
		Await();
		login.getAttribute();
		scrollToElementAndClick(driver, login.Submit);
		Await();
		driver.switchTo().defaultContent();
		login.frameswitch2();
		Await();
		login.ClickonGo.click();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameswitch2();
		Await();
		login.OrderStatus_Released_Validation();
		Await();
		login.driver.switchTo().defaultContent();
		Await();
		Await();
		login.Clipboard_Click();
		login.StatusUpdatetoScanTool_Validation();
		login.OrderPage_RequiredStatus_Yes_Validation();
		Await();
		driver.close();
		Await();
		ArrayList<String> tab2 = new ArrayList<>(driver.getWindowHandles());
		driver.switchTo().window(tab2.get(1));
		login.driver.switchTo().defaultContent();
		Await();
		login.SwitchtoOrdersPAR();
		login.driver.switchTo().defaultContent();
		Await();
		login.frameSwitch();
		Await();
		login.SwitchtoPODReview();
		login.driver.switchTo().defaultContent();
		Thread.sleep(7000);
		Await();
		Await();
		Await();
		Await();
		login.frameSwitch();
		Await();
		login.OrderSearchandFilter();
		Await();
		login.Validate_Status_Released();
		login.Validate_Attachment_No();
		Await();
		login.CheckBox_Click.click();
		Await();
		login.Attach_POD_Click.click();
		Await();
		login.Attach_File();
		login.Attachment_Save();
		Await();
		Thread.sleep(7000);
		Await();
		Await();
		login.OrderSearchandFilter();
		Await();
		Thread.sleep(7000);
		Await();
		Await();
		login.Validate_Attachment_Yes();
		Await();
		login.Validate_Status_POD_Received();
		Await();
		Await();
		Await();
		Await();
		login.CheckBox_Click.click();
		Await();
		login.Attach_POD_Click.click();
		Await();
		login.Attachment_Save();
	}
}